### ISSUE TITLE
Consolidate sell_percent with sell

### ISSUE THREAD

**Issue by zillionare** [zillionare/trader-client#4]
Now we have both sell_percent and sell for selling stock shares. The first one is for sell a portion of the stock shares, the second one is for sell stock shares by absolute amount. However, since the mimimum amount of stock shares to deal with is 100, so we can simply have this:

1. if shares is among 0 and 1, then the argument is the percentage of shares to sell.
2. otherwise, it's the absolute amount of the shares to be sold.

Thus the signature of the function is:

```
def sell(security: str, shares: float, price: Optional[float] = None, order_time: Optional[datetime] = None, **kwargs) -> Dict:
""" sell held stock shares

    Args:
        security: the security to sell
        shares: the number of shares to sell, if it's (0, 1], then it's the percentage of shares to sell, otherwise it's the absolute amount of shares to sell
        price: the price to sell at (optional), if not present, convert it to a market_sell
        order_time: the time of the order (optional), required at backtest mode
    Keyword Args:
        limit_price: the limit price to sell at, if it's a market sell
"""
```
